base/urls.py
from django.urls import path

from . import views


app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

personalSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path(settings.ADMIN_SITE, admin.site.urls),
    path('', include('base.urls', namespace='base'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class PersonalUser(AbstractUser):
    pass

base/models.py
from django.db import models
from taggit.managers import TaggableManager


class Testimonial(models.Model):
    reference_name = models.CharField(max_length=150)
    reference_title = models.CharField(max_length=200)
    reference_testimonial = models.TextField()
    reference_url = models.URLField(blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('reference_name',)

    def __str__(self):
        return self.reference_name


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    repo = models.URLField()
    demo = models.URLField(blank=True, null=True)
    screenshot = models.URLField(blank=True, null=True)
    project_created = models.DateField(db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('project_created',)

    def __str__(self):
        return self.name


class Experience(models.Model):
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    start = models.DateField()
    end = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-start',)

    def __str__(self):
        return self.company


class ExperienceItem(models.Model):
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE, related_name='experienceitems')
    bullet = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.bullet

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class PersonalUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'email',
            'username',
        )


class PersonalUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'email',
            'username',
        )

accounts/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.shortcuts import render
from taggit.models import Tag

from .models import Testimonial, Project, Experience


def home(request):
    testimonials = Testimonial.objects.all()
    projects = Project.objects.all()
    experiences = Experience.objects.all()
    tags = Tag.objects.all()
    context = {
        'testimonials': testimonials,
        'projects': projects,
        'experiences': experiences,
        'tags': tags,
    }
    return render(request, 'base/index.html', context)


def about(request):
    testimonials = Testimonial.objects.all()
    return render(request, 'base/about.html', {'tesimonials': testimonials})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock title %}</title>

        <meta content="" name="description">
        <meta content="" name="keywords">
        <link href="/static/img/Logo_final_Color_600.png" rel="icon">
        <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
        <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
        <link href="/static/vendor/remixicon/remixicon.css" rel="stylesheet">
        <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

        <!-- Template Main CSS File -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>
    <body>
{#        {% include 'base/navbar.html' %}#}
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
      <!-- Vendor JS Files -->
          <script src="/static/vendor/purecounter/purecounter_vanilla.js"></script>
          <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
          <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
          <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
          <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
          <script src="/static/vendor/waypoints/noframework.waypoints.js"></script>
          <script src="/static/vendor/php-email-form/validate.js"></script>

          <!-- Template Main JS File -->
        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

templates/base/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Me{% endblock title %}

{% block content %}
<!-- ======= About Me ======= -->
<div class="about-me container">
  <div class="section-title">
      <h2>About</h2>
      <p>Learn more about me</p>
  </div>

  <div class="row">
    <div class="col-lg-4" data-aos="fade-right">
      <img src="/static/img/pexels-neosiam-685674.jpg" class="img-fluid" alt="">
    </div>
    <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
      <h3>Aerospace Engineer & Software Developer</h3>
      <p class="fst-italic">
        Welcome to my page! I'm an engineer who just likes to build things. Rockets, rovers, drones, apps,
          websites. I have a wide range of interests and experience that brings surprising insight to the
          projects I'm on.
      </p>
      <div class="row">
        <div class="col-lg-6">
          <ul>
            <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>You're here!</span></li>
              <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong> <span>
                  <a href="mailto:chris.mcglownjr@tutanota.com" target="_blank">chris.mcglownjr@tutanota.com</a></span></li>
            <li><i class="bi bi-chevron-right"></i> <strong>Location:</strong> <span>Toledo, OH, USA</span></li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul>
            <li><i class="bi bi-chevron-right"></i> <strong>School:</strong> <span>University of Cincinnati</span></li>
            <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Bachelors of Science in Aerospace Engineering</span></li>
            <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>
          </ul>
        </div>
      </div>
        <p>
            I was born in Toledo, OH and graduated from <strong>University of Cincinnati</strong> where I
            majored in Aerospace Engineering. While at UC I was part of the Autonomous Systems Lab where we
            designed a robotic chassis that interfaced with a Mitsubishi industrial robotic arm used to study
            satellite capture techniques and remote brain surgery. I was a <i>"Rocket Surgeon"</i> for a short
            time. This is also when I started coding, not just for school projects but for research with the
            university as I would often get requests from professors who have an old Fortran code they want to
            revive.
        </p>
        <p>
            The University of Cincinnati has a mandatory co-op system where you are required to complete a certain
            number of internships before you graduate. I did all my internships with the <strong>Air Force Research
            Laboratory</strong> at both Edwards AFB, CA and Wright-Patterson AFB, OH. My focus during this time was
            amassing expertise in <strong>Computational Fluid Dynamics</strong> and the regimes I studied was
            external flow, steady-state, internal combustion, and hypersonics. This is also the time I wrote a lot
            more software because sometimes you have to write your own solvers.
        </p>
        <p>
            I'm now focusing on software development. I have taught myself <strong>Python, C#, SQL, Bash, HTML,
            CSS, and Fortran</strong> preferring to work in Python, C#, and SQL. I've built websites, converted
            excel toolkits to Python toolkits, written desktop applications in C#, and revived Fortran code for
            current computers. Currently, I'm studying cloud technology (AWS) and data analytics. I'm always
            learning and improving.
        </p>
    </div>
  </div>

</div><!-- End About Me -->

<!-- ======= Skills  ======= -->
<div class="skills container">
    <div class="section-title">
        <h2>Skills</h2>
    </div>
    <div class="row skills-content">
        <div class="col-lg-4">
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Python</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>C#</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>SQL</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>HTML</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>CSS</strong> </li>
            </ul>
        </div>
        <div class="col-lg-4">
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Git</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Fortran</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Bash</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Matlab & Simulink</strong> </li>
            </ul>
            <ul>
                <li><i class="bi bi-chevron-right"></i><strong>Javascript/Typescript</strong> </li>
            </ul>
        </div>
    </div><!-- End Skills -->

    <div class="section-title">
        <h2>Technologies</h2>
    </div>

    <div class="row skills-content">
      <div class="col-lg-4">
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>.NET/.NET Core</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>ASP.NET</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Django</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>PostgreSQL</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Amazon Web Services</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Jenkins</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Docker</strong> </li>
          </ul>
      </div>
      <div class="col-lg-4">
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Solid Works</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>AutoCAD LT & Fusion 360</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Unigraphics NX</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Rhinoceros CAD</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Gambit</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Pointwise</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Tecplot</strong> </li>
          </ul>
      </div>
      <div class="col-lg-4">
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Metacomp CFD++ & MIME</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Ansys Fluent & CFX</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Linux</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>OpenFOAM</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>JetBrains IDEs</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Angular</strong> </li>
          </ul>
          <ul>
            <li><i class="bi bi-chevron-right"></i><strong>Paraview</strong> </li>
          </ul>
      </div>

</div><!-- End Technologies -->
</div>

<!-- ======= Interests ======= -->
<div class="interests container">

  <div class="section-title">
    <h2>Interests</h2>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-4">
      <div class="icon-box">
        <i class="ri-open-source-line" style="color: #00a7c6;"></i>
        <h3>Linux</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
      <div class="icon-box">
        <i class="ri-code-box-line" style="color: #5578ff;"></i>
        <h3>Programming</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
      <div class="icon-box">
        <i class="ri-command-line" style="color: #e80368;"></i>
        <h3>Drones</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">
      <div class="icon-box">
        <i class="ri-switch-line" style="color: #e361ff;"></i>
        <h3>Console Gaming</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-book-mark-line" style="color: #47aeff;"></i>
        <h3>Reading</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-bit-coin-line" style="color: #ffa76e;"></i>
        <h3>Crypto</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-steam-line" style="color: #11dbcf;"></i>
        <h3>Steam Deck</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-moon-clear-line" style="color: #4233ff;"></i>
        <h3>Astronomy</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-microscope-line" style="color: #b2904f;"></i>
        <h3>Science</h3>
      </div>
    </div>
    <div class="col-lg-3 col-md-4 mt-4">
      <div class="icon-box">
        <i class="ri-cpu-line" style="color: #b20969;"></i>
        <h3>Technology</h3>
      </div>
    </div>
  </div>

</div><!-- End Interests -->

<!-- ======= Testimonials ======= -->
<div class="testimonials container">
    <div class="section-title">
    <h2>Testimonials</h2>
  </div>
    <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
        <div class="swiper-wrapper">
            {% for testimonial in testimonials %}
            <div class="swiper-slide">
                <div class="testimonial-item">
                    <p>
                        <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                          {{ testimonial.reference_testimonial|truncatewords:75 }}
                        <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                    </p>
                    <img src="{% if testimonial.image_url is not Null %}{{ testimonial.image_url }}{% else %}
                        {% static "img/no_photo.png" %}{% endif %}" class="testimonial-img" alt="">
                    <h3><a href="{{ testimonial.reference_url }}">{{ testimonial.reference_name }}</a> </h3>
                    <h4>{{ testimonial.reference_title }}</h4>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="swiper-pagination"></div>
    </div>
    <div class="owl-carousel testimonials-carousel"></div>
</div><!-- End Testimonials  -->
{% endblock content %}

templates/base/contact.html
<div class="container">
  <div class="section-title">
    <h2>Contact</h2>
    <p>Get In Touch</p>
  </div>
  <div class="row mt-2">
    <div class="col-md-12 d-flex align-items-center">
      <div class="info-box">
        <i class="bx bx-user-check"></i>
        <h3>Send a message</h3>
        <p>I'm always looking for new opportunities. Send me a message and let's have a conversation about any projects
        or job opportunities that you may have in mind. </p>
      </div>
    </div>
    <div class="col-md-6 mt-4 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-envelope"></i>
        <h3>Email Me</h3>
        <a href="mailto:chris.mcglownjr@tutanota.com" target="_blank">chris.mcglownjr@tutanota.com</a>
      </div>
    </div>
    <div class="col-md-6 mt-4 d-flex align-items-stretch">
      <div class="info-box">
        <i class="bx bx-share-alt"></i>
        <h3>Social Profiles</h3>
        <div class="social-links">
          <a href="https://gitlab.com/cmcglownjr" class="gitlab"><i class="ri-gitlab-fill"></i></a>
          <a href="https://www.linkedin.com/in/chrismcglownjr" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

templates/base/experience-item.html
{% for exp in experience %}
<div class="resume-item">
    <h4>{{ exp.company }}</h4>
    <h5>{{ exp.start|date:"F Y" }} - {% if exp.end is Null %}Present{% else %}{{ exp.end|date:"F Y" }}
    {% endif %}</h5>
    <p><em>{{ exp.location }} </em></p>
    <p>
        <ul>
            {% for item in exp.experienceitems.all %}
                <li>{{ item.bullet }}</li>
            {% endfor %}
        </ul>
    </p>
</div>
{% endfor %}

templates/base/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chris McGlown Jr{% endblock title %}

{% block content %}
<header id="header">
    <div class="home-header container">
        <h1><a href="{% url 'base:home' %}">Chris McGlown Jr.</a></h1>
        <h2>I'm a passionate <span>Aerospace Engineer and Software Developer</span> who likes to build amazing
            projects</h2>
        {% include 'base/navbar.html' %}
        <div class="social-links">
            <a href="https://gitlab.com/cmcglownjr" class="gitlab"><i class="ri-gitlab-fill"></i></a>
            <a href="https://www.linkedin.com/in/chrismcglownjr" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
    </div>
</header>
{% endblock content %}

templates/base/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chris McGlown Jr{% endblock title %}

{% block content %}
    <!-- ======= Header ======= -->
    <header id="header">
        <div class="container">
            <h1><a href="{% url 'base:home' %}">Chris McGlown Jr.</a></h1>
            <h2>I'm a passionate <span>Aerospace Engineer and Software Developer</span> who likes to build amazing
                projects</h2>
            {% include 'base/navbar.html' %}
            <div class="social-links">
                <a href="https://gitlab.com/cmcglownjr" class="gitlab"><i class="ri-gitlab-fill"></i></a>
                <a href="https://www.linkedin.com/in/chrismcglownjr" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
        </div>
    </header><!-- End Header -->
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        {% include 'base/about.html' %}
    </section><!-- End About Section -->
    <!-- ======= Resume Section ======= -->
    <section id="resume" class="resume">
        {% include 'base/resume.html' %}
    </section><!-- End Resume Section -->
    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
        {% include 'base/portfolio.html' %}
    </section><!-- End Portfolio Section -->
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        {% include 'base/contact.html' %}
    </section><!-- End Contact Section -->

    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
{% endblock content %}

templates/base/navbar.html
<nav id="navbar" class="navbar">
    <ul>
      <li><a class="nav-link active" href="#header">Home</a></li>
      <li><a class="nav-link" href="#about">About</a></li>
      <li><a class="nav-link" href="#resume">Resume</a></li>
      <li><a class="nav-link" href="#portfolio">Portfolio</a></li>
      <li><a class="nav-link" href="#contact">Contact</a></li>
    </ul>
    <i class="bi bi-list mobile-nav-toggle"></i>
    <script src="/static/js/main.js"></script>
</nav><!-- .navbar -->

templates/base/portfolio-item.html
{% load static %}
{% load base_tags %}
<div class="row">
    <div class="col-lg-12 d-flex justify-content-center">
        <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">All</li>
            {% for tag in tag_filters %}
                <li data-filter={{ tag.slug }}>{{ tag.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="row portfolio-container">
  {% for project in project_data %}
      <div class="col-lg-4 col-md-6 portfolio-item{% for ptag in project.tags %}{{ ptag }}{% endfor %}">
          <div class="portfolio-wrap">
              <img src="{{ project.project.screenshot }}" class="img-fluid" alt="">
              <div class="portfolio-info">
                  <h4>{{ project.project.name }}</h4>
                  <p>{{ project.project.description|truncatewords:50 }}</p>
                  <div class="portfolio-links">
                      <a href="{{ project.project.screenshot }}" data-gallery="portfolioGallery"
                         class="portfolio-lightbox" title="{{ project.project.name }}"><i class="bx bx-plus"></i></a>
                      <a href="{{ project.project.repo }}" target="_blank"><i class="bx bx-link"></i></a>
                  </div>
              </div>
          </div>
      </div>
  {% endfor %}
</div>

templates/base/portfolio.html
{% load base_tags %}
{% load static %}

<div class="container">
    <div class="section-title">
        <h2>Portfolio</h2>
        <p>My Projects</p>
    </div>
    {% project_card %}
</div>

templates/base/resume.html
{% load base_tags %}
{% load static %}

<div class="container">
    <div class="section-title">
        <h2>Resume</h2>
        <p>My Experiences</p>
    </div>

    <div class="row">

        <div class="col-lg-6">
            <h3 class="resume-title">Education</h3>
            <div class="resume-item pb-0">
                <h4>Bachelor of Science in Aerospace Engineering</h4>
                <h5>2005 - 2010</h5>
                <p><em>University of Cincinnati, Cincinnati, OH, USA</em></p>
                <p>The University of Cincinnati’s B.S. in Aerospace Engineering Degree is the country’s second oldest
                    program of its kind. Aerospace engineering takes a deep exploration of advanced science and
                    technology in the design and development of flight vehicles; degree study includes the analysis and
                    design of aircraft, spacecraft, missiles, rockets, and satellites.</p>
                <p><a href="https://ceas.uc.edu/academics/departments/aerospace-engineering-mechanics/degrees-programs/aerospace-engineering-bachelor-of-science.html">
                    - University of Cincinnati</a> </p>
            </div>
        </div>
        <div class="col-lg-6">
            <h3 class="resume-title">Certifications</h3>
            <div class="resume-item col-lg-auto">
                <a href="https://www.credly.com/badges/9597c4ec-34e3-45f0-a8f0-3c4d26cc06ff/public_url" target="_blank">
                    <img src="/static/img/certifications/aws-certified-cloud-practitioner.png"
                         alt="AWS certified cloud practitioner" width="128">
                </a>
            </div>
            <div class="resume-item col-lg-auto">
                <a href="https://www.credly.com/badges/5ed96030-348a-40ea-99f6-335982af45b2/public_url" target="_blank">
                    <img src="/static/img/certifications/google-data-analytics-certificate.2.png"
                         alt="Google data analytics" width="128">
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <h3 class="resume-title">Professional Experience</h3>
        <div class="col-lg-6">
            {% show_experience 'left' %}
        </div>
        <div class="col-lg-6">
            {% show_experience 'right' %}
        </div>
    </div>
</div>